CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes 
LAYER_LOCK_ENABLE = yes
LEADER_ENABLE = yes
TAP_DANCE_ENABLE = yes 
SEND_STRING_ENABLE = yes
REPEAT_KEY_ENABLE = yes
LUMBERJACK_ENABLE =no
CONSOLE_ENABLE = yes

SRC += leader_key.c